<?php
/**
 * IQS FRAMEWORK CORE FILE
 *
 * READ ONLY for downstream project programmers.
 * Do not modify this file directly in template or cloned projects.
 * Custom changes must be implemented in project-specific files
 * or approved extension points.
 */declare(strict_types=1);

return [
    [
        'key' => 'recipient_name',
        'label' => 'Recipient Name',
        'group' => 'recipient',
        'description' => 'Nama penuh penerima emel.',
        'sample_value' => 'Ali Bin Ahmad',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'recipient_email',
        'label' => 'Recipient Email',
        'group' => 'recipient',
        'description' => 'Alamat emel penerima.',
        'sample_value' => 'ali@example.com',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'recipient_role',
        'label' => 'Recipient Role',
        'group' => 'recipient',
        'description' => 'Peranan penerima seperti staff, student, public, atau admin.',
        'sample_value' => 'staff',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'recipient_position',
        'label' => 'Recipient Position',
        'group' => 'recipient',
        'description' => 'Jawatan atau posisi penerima.',
        'sample_value' => 'Pegawai Tadbir',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'recipient_department',
        'label' => 'Recipient Department',
        'group' => 'recipient',
        'description' => 'Jabatan atau unit penerima.',
        'sample_value' => 'Bahagian Teknologi Maklumat',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'organization_name',
        'label' => 'Organization Name',
        'group' => 'organization',
        'description' => 'Nama penuh organisasi.',
        'sample_value' => 'Universiti Pertahanan Nasional Malaysia',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'organization_short',
        'label' => 'Organization Short Name',
        'group' => 'organization',
        'description' => 'Nama ringkas organisasi.',
        'sample_value' => 'UPNM',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'system_name',
        'label' => 'System Name',
        'group' => 'system',
        'description' => 'Nama sistem semasa.',
        'sample_value' => 'e-Base',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'support_email',
        'label' => 'Support Email',
        'group' => 'system',
        'description' => 'Alamat emel sokongan sistem.',
        'sample_value' => 'support@example.com',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'sender_name',
        'label' => 'Sender Name',
        'group' => 'sender',
        'description' => 'Nama penghantar emel.',
        'sample_value' => 'System Administrator',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'current_date',
        'label' => 'Current Date',
        'group' => 'date',
        'description' => 'Tarikh semasa dalam format paparan sistem.',
        'sample_value' => '02 April 2026',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'current_datetime',
        'label' => 'Current Datetime',
        'group' => 'date',
        'description' => 'Tarikh dan masa semasa.',
        'sample_value' => '02 April 2026 10:30 AM',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'current_year',
        'label' => 'Current Year',
        'group' => 'date',
        'description' => 'Tahun semasa.',
        'sample_value' => '2026',
        'source_type' => 'general',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'office_label',
        'label' => 'Office Label',
        'group' => 'bdr',
        'description' => 'Nama lokasi kerja BDR seperti Kampus UPNM atau HAT Tuanku Mizan.',
        'sample_value' => 'Kampus UPNM',
        'source_type' => 'bdr',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'office_address',
        'label' => 'Office Address',
        'group' => 'bdr',
        'description' => 'Alamat lokasi kerja BDR yang digunakan untuk kiraan jarak.',
        'sample_value' => 'Universiti Pertahanan Nasional Malaysia',
        'source_type' => 'bdr',
        'is_general' => 1,
        'is_active' => 1,
    ],
    [
        'key' => 'site_code',
        'label' => 'Site Code',
        'group' => 'bdr',
        'description' => 'Kod lokasi kerja BDR untuk konteks multi-site.',
        'sample_value' => 'upnm_kampus',
        'source_type' => 'bdr',
        'is_general' => 1,
        'is_active' => 1,
    ],
];
