services:
  web:
    build: .
    container_name: survey-uat-web   # ✅ tukar nama
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html
      - ./VERSION:/var/www/VERSION:ro

      # ✅ tukar ke config baru
      - ./docker/apache/survey-uat.dev.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/apache/servername.conf:/etc/apache2/conf-enabled/servername.conf

      - ./docker/ssl:/etc/apache2/ssl
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini

    environment:
      IS_DOCKER: "1"
      APP_VERSION_FILE: "/var/www/VERSION"