# HTTP → HTTPS
server {
    listen 80;
    server_name survey-uat.upnm.edu.my;
    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl http2;
    server_name survey-uat.upnm.edu.my;

    root /var/www/survey-uat/public;
    index index.php index.html;

    ssl_certificate     /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/upnm.key;

    access_log /var/log/nginx/survey-uat.access.log;
    error_log  /var/log/nginx/survey-uat.error.log;

    error_page 404 = /request-unavailable.php;

    location = /request-unavailable.php {
        internal;

        include fastcgi_params;
        fastcgi_pass unix:/run/php/survey-uat84.sock;

        fastcgi_param SCRIPT_FILENAME $document_root/request-unavailable.php;
    }

    location ~ /\. {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass unix:/run/php/survey-uat84.sock;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_intercept_errors on;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg)$ {
        expires 7d;
        access_log off;
    }
}
